### ISSUE TITLE
Split Schema Migrator images for different databases 

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#1063]
**Description**

Recently there were several failures caused by Schema Migrator, meaning images of components did not match the images of migrator, as single Schema Migrator image is used by 3 different databases.

I suggest splitting Schema Migrator to different images so that such conflicts do not occur in the future.

**Reasons**

You need to be very careful when bumping the image of Schema Migrator, to not migrate the database of the different components from which corresponding changes are not yet reflected in a currently used version (meaning image was not bumped yet).

We have already experienced (at least three times) issues caused by this exact scenario.

**Comment by aszecowka** [comment]
It seems that we have to update only `values.yaml` file and add possibility to configure different images for different databases:
```
    schema_migrator:
      dir:
      version: "PR-1042"
```
to:
```
    director_schema_migrator:
      dir:
      version: "PR-1042"

    provisioner_schema_migrator:
      dir:
      version: "PR-1042"
```
