### ISSUE TITLE
Provisioner updates Director with Runtime information

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#1149]
**Description**

In the current implementation, there is no information propagated to the Director on what is the status of Runtime provisioning/installation. This may lead to the lack of information on how to access the Runtime and what steps should be taken in order to make that Runtime work properly. We would like to have an easy access to the following information:
- Gardener cluster name
- Gardener cluster domain
- Provisioning status
- Installation status

The proposal is to label Runtime via Director's API, the above data can be fetched from the following sources:

Gardener cluster name:
`metadata.name` value in Shoot CR

Gardener cluster domain
`spec.dns.domain` value in Shoot CR

Provisioning status (annotations created by the Provisioner):
```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/provisioning: provisioned
    compass.provisioner.kyma-project.io/provisioning-step: provisioning-finished
```
Installation status (annotations created by the Provisioner):
```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/kyma-installation: installed
    compass.provisioner.kyma-project.io/kyma-installation-timestamp: '2020-04-06T14:17:37.674Z'
```

**Reasons**

We want the user to be updated on what is the current status of Runtime provisioning / Kyma installation.
