### ISSUE TITLE
compass-installer container got OOM Killed

### ISSUE THREAD

**Issue by life0215** [kyma-incubator/compass#1506]
**Description**
When installing compass, we are constantly getting OOM Killed issue for compass installer pod.
It happened on mps dev. (the current memory limit is 1G)

```yaml
Containers:
  compass-installer-container:
    Container ID:  docker://c50baa356bbc25fdec7fba5ef306d6ce7b168ca14dfb6cd0543389d777ff52ec
    Image:         eu.gcr.io/kyma-project/compass-installer:master-0a605baa-1594971992
    Image ID:      docker-pullable://eu.gcr.io/kyma-project/compass-installer@sha256:ae2871ff7b92f83ef53601e9f71d8a3eeca114ebfb0dd523ddb5d56a581f7227
    Port:          <none>
    Host Port:     <none>
    Args:
      -overrideLogFile=/app/overrides.txt
      -helmDebugMode=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 28 Jul 2020 12:11:15 +0800
      Finished:     Tue, 28 Jul 2020 12:11:48 +0800
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     400m
      memory:  1Gi
    Requests:
      cpu:     40m
      memory:  32Mi
```

**Expected result**
The installation should continue without OOM issue 

**Actual result**
compass installer container got OOM Killed

**Steps to reproduce**

**Troubleshooting**

**Comment by life0215** [comment]
If the memory usage is expected to be higher than 1G at some point, we will need to increase the [limit](https://github.com/kyma-incubator/compass/blob/05645f5ba9b80ee40621df8bff096b11e902fbb5/installation/resources/installer.yaml#L223) correspondingly.

**Comment by life0215** [comment]
Manually increased the limits to 2Gi on dev as temp fix

**Comment by life0215** [comment]
similar issue happened to kcp-installer 
```yaml
Containers:
  kcp-installer-container:
    Container ID:  docker://cc928a275eb329606ea88795e7615796246fed48bc6efa932b6ca6d7d5ed7c76
    Image:         eu.gcr.io/kyma-project/kcp-installer:master-a2ee860c-1595855974
    Image ID:      docker-pullable://eu.gcr.io/kyma-project/kcp-installer@sha256:fd41f2b2dff06ab549bc14cfab61513c885681e634453a055b3f60fa8e5e3e89
    Port:          <none>
    Host Port:     <none>
    Args:
      -overrideLogFile=/app/overrides.txt
      -helmDebugMode=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 28 Jul 2020 14:34:19 +0800
      Finished:     Tue, 28 Jul 2020 14:34:50 +0800
    Ready:          False
    Restart Count:  11
    Limits:
      cpu:     400m
      memory:  1Gi
    Requests:
      cpu:     40m
      memory:  32Mi
    Environment:
      INST_RESOURCE:        kcp-installation
      OVERRIDES_NAMESPACE:  kcp-installer
```
