### ISSUE TITLE
Tenant storage and Business tenant to compass tenant mapping service

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#584]
**Description**
This ticket is about to make Compass Components to work with external tenants and then internally find a mapping to internal one. It must also work opposite direction when Director calls external TokenService with external tenant. 

**AC**
- allow to store tenants and open only query API to get external tenants. About exposed API discuss with Hasselhoff team to make it nice for UI, see: https://github.com/kyma-project/console/issues/1486
- creation, upgrades and deletion and also mapping between external/internal tenants will be done internally 
- only admin user sees all tenants from query API

**Comment by dbadura** [comment]
WIP: 
1. Create database table with mapping between internal and external tenant (external tenant can be whatever) and we should keep something like external tenant provider name to distinguish tenants.
2. Tenant mapping service use this table to map external tenant to internal tenant
3. When doing request to external token service, we will use external tenant.
4. Add integration tests, which will:
  * register something with external tenant 
  * check if compass will call external TokenService

**Comment by aszecowka** [comment]
After dicussion with KK, in the first iteration we can provide graphQL queries which returns the same data as are already stored in the configmap:
```
  tenants:
    - name: default
      id: 3e64ebae-38b5-46a0-b1ed-9ccee153a0ae
    - name: foo
      id: 1eba80dd-8ff6-54ee-be4d-77944d17b10b
    - name: bar
      id: 9ca034f1-11ab-5b25-b76f-dc77106f571d

```
