### ISSUE TITLE
[MVP] KEB sends components list to Provisioner 

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#691]
**Description**

Kyma Environment Brokers should send to provisioner the kyma version together with the components list that should be installed. We need to take care also about the optional and required ones - all of them need to be specified in proper order. 

There is an agreement that Service Manager and uaa activator need to be enabled in this task:

- [service-manager-proxy](https://github.com/kyma-project/kyma/tree/master/resources/service-manager-proxy)
    component:
    ```yaml
      - name: service-manager-proxy
        namespace: kyma-system
    ```

    and setting proper overrides:
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: service-manager-proxy-overrides
      namespace: kyma-installer
      labels:
        installer: overrides
        component: service-manager-proxy
        kyma-project.io/installation: ""
    data:
      sm.password: "pass"
      sm.user: "username"
      config.sm.url: "service_manager_url"
    ```
- [uaa-activator](https://github.com/kyma-project/kyma/tree/master/resources/uaa-activator)
    component:
    ```yaml
      - name: uaa-activator
        namespace: kyma-system
    ```

  _Now overrides needed_
