### ISSUE TITLE
KEB supports source.url feature from kyma installer

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#940]
**Description**

KEB supports source.url feature from kyma installer.

Example: installer
```
  ...
  - name: knative-eventing-channel-kafka
    namespace: knative-eventing
    release: ""
  - name: knative-eventing-channel-kafka-tests
    namespace: knative-eventing
    release: ""
  - name: prometheus-config-updater
    namespace: kyma-system
    release: ""
  url: ""
  version: 0.0.1
...
```
Example: broker
```
...
      - name: "knative-eventing-channel-kafka"
        namespace: "knative-eventing"
        source:
          url: "github.com/kyma-incubator/knative-kafka.git//resources/knative-kafka?ref=master"
      - name: "knative-eventing-channel-kafka-tests"
        namespace: "knative-eventing"
      - name: "prometheus-config-updater"
        namespace: "kyma-system"
        release: ""
        source:
          url: "https://storage.googleapis.com/kyma-mps-dev-artifacts/prometheus-config-updater.zip"
...
```

**AC**
- makes above broker configuration available in KEB
