### ISSUE TITLE
Adjust Shoot cluster specification values in Provisioner

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#951]
**Description**

In order to fulfill security standards, we would need to make sure the following points are addressed:
- <s>`SecurityContextDeny` is added as one of AdmissionPlugins in `Shoot.ShootSpec.Kubernetes.KubeApiServerConfig.AdmissionPlugins`</s>
- `Shoot.ShootSpec.Kubernetes.KubeApiServerConfig.enableBasicAuthentication` is set to false
- <s>`Shoot.ShootSpec.Kubernetes.allowPrivilegedContainers` is set to false</s>

**Acceptance Criteria**
- Above specs configured to desired values

**Comment by janmedrek** [comment]
Disabling `Shoot.ShootSpec.Kubernetes.allowPrivilegedContainers` is actually problematic due to Kyma installation being based on Tiller, which requires this parameter to be set to true. We cannot simply address this point, but the issue will be solved during the switch to Helm 3.0 (which no longer uses Tiller as an installation mechanism).

**Comment by rafalpotempa** [comment]
There exists an issue with enabling `SecurityContextDeny` on Gardener caused by Calico configuration `allowPrivillageEscalation: true` which blocks Tiller setup and leads to failure of Kyma Runtime installation.

Gardener Issue:
https://github.com/gardener/gardener-extension-networking-calico/issues/19

**Comment by mvladev** [comment]
Several points:

- `SecurityContextDeny` admission plugin should only be enabled if `PodSecurityPolicy` admission [plugin is not enabled](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny). Gardener has enabled `PodSecurityPolicy` controller for quite a while - https://github.com/gardener/gardener/pull/226 
- `Shoot.ShootSpec.Kubernetes.allowPrivilegedContainers` controls if the group `system:authenticated` is allowed to use the full Pod security features ( as if PSP is not enabled ). Setting this value to `true` or `false` have no effect on the `PodSecurityPolicy` admission plugin which is always enabled.

> Disabling Shoot.ShootSpec.Kubernetes.allowPrivilegedContainers is actually problematic due to Kyma installation being based on Tiller, which requires this parameter to be set to true. We cannot simply address this point, but the issue will be solved during the switch to Helm 3.0 (which no longer uses Tiller as an installation mechanism).

I would guess this is because Tiller doesn't provide any `PodSecurityPolicy` or it's assigned the `gardener:unprivileged` PSP. You can workaround this by allowing tiller's service account to the `gardener:privilegeed` PSP.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-psp
  namespace: tiller-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:unprivileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: tiller
  namespace: tiller-ns
```

For reference here are the PSPs which gardener deploy on every single cluster:

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    garden.cloud/description: |
      gardener.privileged allows full unrestricted access to Pod features, as if the PodSecurityPolicy controller was not enabled.
    garden.sapcloud.io/description: |
      gardener.privileged allows full unrestricted access to Pod features, as if the PodSecurityPolicy controller was not enabled.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.privileged
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    garden.sapcloud.io/description: |
      gardener.unprivileged grants the mininimum amount of privileges necessary to run non-privileged Pods.
      This policy cannot be tuned down, but can be used as a template.
    gardener.cloud/description: |
      gardener.unprivileged grants the mininimum amount of privileges necessary to run non-privileged Pods.
      This policy cannot be tuned down, but can be used as a template.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default,docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.unprivileged
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65534
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65534
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
```

**Comment by mvladev** [comment]
For further reference, here are the `ClusterRoles` for those PSPs:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:privileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:unprivileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

At this moment regardless of the flag `.spec.kubernetes.allowPrivilegedContainers`, all authenticated users are allowed to use the `gardener.unprivileged` PSP:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    gardener.cloud/description: |
      Allow all authenticated users to use the unprivileged PSP.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:unprivileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:unprivileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

We might change this in the future and if you set `.spec.kubernetes.allowPrivilegedContainers: false`, this `ClusterRoleBinding` would be:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    gardener.cloud/description: |
      Allow all authenticated users to use the unprivileged PSP.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:unprivileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:unprivileged
subjects: []
```

If `.spec.kubernetes.allowPrivilegedContainers: true`, then all authenticated users are allowed to use all pod features.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    gardener.cloud/description: |
      Allow all authenticated users to use the privileged PSP.
      The subject field is configured via .spec.kubernetes.allowPrivilegedContainers flag on the Shoot resource.
      Do not manually change it as it'll be reconciled back to the original state.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:privileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

If `.spec.kubernetes.allowPrivilegedContainers: false`, then nobody (outside of `kube-system` ns) is allowed users are allowed to use all pod features:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    gardener.cloud/description: |
      Allow all authenticated users to use the privileged PSP.
      The subject field is configured via .spec.kubernetes.allowPrivilegedContainers flag on the Shoot resource.
      Do not manually change it as it'll be reconciled back to the original state.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud:psp:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:privileged
subjects: []
```
